### ISSUE TITLE
JAWS reads last line of contents in textarea twice

### ISSUE THREAD

**Issue by olegbuchnev** [FreedomScientific/standards-support#178]
### Summary

Move caret in textarea anywhere except end of last string and push insert + down arrow shortcut ("say all")

### Example

https://jsfiddle.net/fy5sc2w1/

### Expected result

JAWS pronounces all contents once

### Actual result

JAWS pronounces last string twice

#### JAWS version and build number

JAWS 2018.1811.2 64-bit
JAWS 2019.1901.66 64-bit
 
#### Browser and version:

Chrome 72 and IE 11

**Comment by JAWS-test** [comment]
I can only reproduce the problem in Chrome. 

In IE 11, the navigation method is not possible when the focus is in textarea (even if Forms Mode is exited). If the focus is outside, INS+Down arrow will only output the content 1x.

**Comment by jducrot** [comment]
@BenKeyFSI I created the following pen to test this out under different conditions: https://cdpn.io/TPG/debug/JjGEbqO

@menovak took a look as well and the results are odd in different ways across Chrome, FF, and IE. The output can be summed up as follow (see test details in the pen):
- JAWS 20 + Chrome 83: Last line is spoken twice
- JAWS 20 + FF 77: Last word is spoken 2-3 times 
- JAWS 20 + IE 11: last word of last line spoken twice
- NVDA + either browser: works as expected

This validates the issue originally reported in 2018. Since it's long standing we're wondering if it's already in the JAWS bug tracker. Would you mind checking?

**Comment by stevefaulkner** [comment]
tested using test case: https://cdpn.io/TPG/debug/JjGEbqO
i don't see a bug here, when the last line is reached, the cursor is at start of the line, when down arrow is pressed, cursor moves to the end of the line and announces the text again. This is exactly the behaviour exhibited by NVDA
