### ISSUE TITLE
Auto Suggest Search not working correctly in Chrome but works in IE

### ISSUE THREAD

**Issue by amberderosa** [FreedomScientific/standards-support#183]
### Summary

> Brief description of the issue. Please list any specific steps.
> 
> Example:
> 1. Go to https://institutional.vanguard.com/web/cf/inst-investor-home/ in Chrome
> 2. Tab to the Search box "Find a fund or search the site"

### Expected result

> Works as expected using JAWS and ie. 

### Actual result

> Using JAWS and Chrome there are three issues. 
Upon first focus in the search combo box, JAWS is reading as use arrow key to navigate but at that time there are no results displayed yet.
Upon search, JAWS is not informing the user with the # of results displayed, 
Upon using the arrow key, user is NOT able to navigate to the search results, focus is going out of the expanded section.
### Example

>> 1. Go to https://institutional.vanguard.com/web/cf/inst-investor-home/ in Chrome
> 2. Tab to the Search box "Find a fund or search the site"
3. Screen reader should say "Region search edit Find a fund or search the site. Type in text
4. Type 500 index fund. You should hear 10 rows are available use up and down arrows to navigate. 

#### JAWS version and build number

JAWS Version 18.0.1835
 
#### Operating System and version

Windows 10

#### Browser and version:

Chrome - Version 68.0.3440.75 (Official Build) (64-bit)

**Comment by menovak** [comment]
hi amberderosa ,

I was able to spend some time reviewing this issue and this is what I've found.  I was testing using JAWS 2018.1807, JAWS 2019.1904, IE11, Firefox 67 and Chrome 75 on Windows 10.

"3. Screen reader should say "Region search edit Find a fund or search the site. Type in text"

I assume you were in screen reader Forms mode (using the TAB key) since in Browse mode (using the arrow keys) a change in the verbosity levels can dictate whether or not the word 'region' is announced, see [Shortish note on JAWS support for regions](https://developer.paciellogroup.com/blog/2018/07/shortish-note-on-jaws-support-for-regions/).

"4. Type 500 index fund. You should hear 10 rows are available use up and down arrows to navigate."

When typing in 500 index fund, all three browsers first returned 8 results, and a second or two later this changed to 10 results.  Ignoring the 8 results, this is what I found when JAWS was running :

**IE11** - announced "10 results are available, use up/down arrow keys to navigate" - upon arrow up/down the first item in the list took focus but JAWS focus (shaded green background) was on the second item and the second item was announced.  I was able to arrow up or down the list and even go back to the first item and it would then announce properly.

**Firefox** - simply announced 'expanded', I was able to arrow up and down the list and JAWS announced each item.  

**Chrome** - announced "expanded, 10 results are available, use up/down arrow keys to navigate" -  upon arrow up/down the first item in the list took focus and JAWS announced it fine, but then I hear a 'low beep' indicating JAWS had changed mode (from Forms mode to Virtual PC Cursor 'On' mode) and I was no longer able to navigate the list UNLESS I switched back to Forms mode, which I should not have to do.

So it appears the newer version of JAWS are understanding the results of the Search better than your previous version (you listed JAW 18.0.1835), but there does seem to be an issue with how focus is managed in the 'search/autocomplete with dropdown listbox' widget when it appears.  I did not spend much time reviewing your source code, but I did notice a few things which are missing according to the WAI-ARIA authoring Practices 1.1 for [comboboxes used with autocomplete](https://www.w3.org/TR/wai-aria-practices-1.1/#combobox).

I believe you should follow the ARIA 1.1 guidance:
- _aria-haspopup_ is missing
- _aria-activedescendant_ is missing 
   "" When a combobox receives focus, DOM focus is placed on the textbox element. ""
   "" When a descendant of a listbox, grid, or tree popup is focused, DOM focus remains on the textbox and the textbox has _aria-activedescendant_ set to a value that refers to the focused element within the popup.""
( I believe adding this will correct the issues with focus noted above)
- once "_aria-activedescendant_" is added, I believe the _tabindex="0"_ on all the item anchor elements (e.g., `<a>`) should be removed as _aria-activedescendant_ uses an ID to reference a list item

Once you have corrected the focus issues with the  'search/autocomplete with dropdown listbox' widget, we can retest using JAWS 2018/2019 again.
