### ISSUE TITLE
JAWS 2018 ignores aria-label on li during sayAll

### ISSUE THREAD

**Issue by corinnaSchultz** [FreedomScientific/standards-support#191]
### Summary
In a UL, when Jaws is reading in response to Say All, it ignores the aria-label of the list item elements, and only reads their content. 
- If I tab or down-arrow to each list item, it will read the aria-label and not the content.
- If I use right-arrow, it ignores the aria-label and reads the content

See attached sample html file.

### Expected result

I expected that JAWS would always read the aria-label text.

### Actual result

The aria-label text was ignored during Say All and right-arrow, but not with down-arrow.

### Example
[sample.txt](https://github.com/FreedomScientific/VFO-standards-support/files/3069605/sample.txt)

#### JAWS version and build number
JAWS 2018.1811.2  (professional)

 
#### Operating System and version
Win 7

#### Browser and version:
Chrome 73
Firefox 66.0.3

**Comment by corinnaSchultz** [comment]
I have read the previous discussion about adding tabindex on arbitrary elements, but I thought the inconsistent behavior between tab and right arrow and down arrow was worth reporting.

My use case:

I am trying to use an unordered list to present options that can be activated with a click or space bar, to control the presentation of extra content. Similar to a tab control, but without the use of the tab related aria roles (very similar to the approach described here: http://simplyaccessible.com/article/danger-aria-tabs/  but without the use of anchor tags).  Apparently this is not a good approach... 

I would like the following behavior:
* items are tabbable (we want to keep a very simple model of keyboard nav, to be friendly to young children, or novice screen reader users), and navigable using down-arrow or list element shortcut keys.
* an announcement of the number of items (e.g. list of three items)
* tab or down arrow will read the content (or aria label) -- I didn't want to use anchor tags because the list item and the link are then treated as two entities to announce, as you navigate through the list with down-arrow or tab. And role=presentation on the list item resulted in the link not being part of the list count.
* user presses space or click to cause the associated content to be visible and other content to become hidden (this is managed via javascript, aria-hidden, and css)

Any suggestions for how to implement this in a non-hacky way would be welcome.

**Comment by menovak** [comment]
hi corinnaSchultz,

When you navigate with JAWS by pressing the TAB key, you generally navigate from active item to active item in what is sometimes called "forms, or Virtual PC Cursor Off, mode" (high beep). If you just start pressing the Up/Down arrow keys, JAWS may have changed into "browse, or Virtual PC Cursor On, mode" (low beep) where JAWS will announce all the text, even the non-visible aria-label text as 
you move up or down the screen.  I'm assuming you are familar with JAWS modes?

Also when you added aria-label to the LI elements and JAWS did not announce it, part of the issue there was that an LI element by itself is not an active element, so you could not TAB to it by default. 

I'm not sure I understand your comment "I didn't want to use anchor tags because the list item and the link are then treated as two entities to announce, as you navigate through the list with down-arrow or tab.", but will something like below work?

`<h1>sample of accName2</h1>`
`<ul>`
`<li><a href="#" aria-label="kittens"></a><span aria-hidden="true"> kittens<span></li>`
`<li><a href="#" aria-label="puppies"></a><span aria-hidden="true"> puppies<span></li>`
`<li><a href="#" aria-label="rodents"></a><span aria-hidden="true"> rodents<span></li>`
`</ul>`

Let me know if I am understanding the issue?
Regards,

Mark, TPG Engineer
