### ISSUE TITLE
hidden text is not getting read by JAWS-19

### ISSUE THREAD

**Issue by domSa10** [FreedomScientific/standards-support#206]
Jaws19 is not reading hidden text. 

Issue-
I have a drop-down element and upon selecting value from it, I am showing one button. This button was not part of DOM. Based on the dropdwon value I am  adding button to DOM and adding hidden text as well with the button.  Hidden text is kind a alert to know user that button is visible on UI.

JAWS-18 was announcing the change on UI but JAWS-19 is not announcing anything adding which is getting added to the DOM on the fly.

**Comment by scottaohara** [comment]
@domSa10 could you provide a test case for your issue?  There's not enough information here to investigate. 

Thank you

**Comment by domSa10** [comment]
@scottaohara  thanks for replying. Here is the [Plunker](https://plnkr.co/edit/keriaXRSDYsDEoc5zBG8?p=preview) link.

Jaws-18 is reading this hidden text. But Jaws-19 is not reading hidden text which is getting added dynamically. If I give "role='alert'" to the div tag, its getting read by jaws. 

I have many dynamic element on page which are getting rendered take time to render in UI based on the response time from the server.

**Comment by JAWS-test** [comment]
In Firefox the live region is output correctly, in Chrome not. IE 11 does not open the page.

Live Region works very differently and unreliably. In Chrome it probably works if the Live Region already exists in the DOM and then only its content is updated.

In the example, the purpose of the Live Region is unclear, because it only outputs that the select has been changed. However, this is also noticeable without Live Region.

See also: https://github.com/w3c/aria-practices/issues/78#issuecomment-524619306

**Comment by stevefaulkner** [comment]
tested with works in firefox, not in chrome, closing for now
