### ISSUE TITLE
Slider - JAWS narrates current and new value in vertical slider

### ISSUE THREAD

**Issue by kolaps33** [FreedomScientific/standards-support#219]
### Summary

> Brief description of the issue. Please list any specific steps.
> 
> Example:
1. Go to https://www.w3.org/TR/wai-aria-practices/examples/slider/slider-2.html
2. Switch off virtual cursor
3. Navigate into vertical slider "Temperature"
4. use up/down arrow keys to change value 

### Expected result
JAWS narrates new value on the slider

### Actual result
JAWS narrate current value and then new value as user press down/up arrow key.
![image](https://user-images.githubusercontent.com/22620150/61208585-09524e80-a6f8-11e9-9b82-af3ef2dcab49.png)

### Example
https://www.w3.org/TR/wai-aria-practices/examples/slider/slider-2.html

### Additional Information
Reproducible with Chrome and Firefox. Other browsers haven't tested. 

#### JAWS version and build number
2019.1906.10

 
#### Operating System and version
Windows 10 Enterprise
version: 1903

#### Browser and version:
Chrome
Version 75.0.3770.100 (Official Build) (64-bit)

Firefox 
68.0 (64-bit)

**Comment by JAWS-test** [comment]
In Chrome and Firefox, the problem only occurs in application mode, so it should not occur as often. The problem also only occurs when navigating up and down with arrow keys. There is no problem with left-right arrow keys.
In IE, the problem is more serious: There is no value output for up and down arrow keys (even without application mode).

In all browsers, the problem occurs regardless of the actual orientation (vertical or horizontal). I would recommend using only horizontal sliders until the problem is fixed - because then the left-right navigation is obvious.

Another problem is that all sliders are displayed with "checked not checked sub men" in the form field list (INS+F5) due to aria-orientation. The problem also occurs with most other ARIA roles that use aria-orientation.

**Comment by stevefaulkner** [comment]
Tested with JAWS 2024.2310.70 and Chrome 119. Works as expected - [test case](https://cdpn.io/pen/debug/oNmpoYg)
