### ISSUE TITLE
Menu item with submenu not perceptible

### ISSUE THREAD

**Issue by JAWS-test** [FreedomScientific/standards-support#415]
### Summary

Example:
1. https://w3c.github.io/aria-practices/examples/menubar/menubar-navigation.html
2. Navigate with Tab to the menu, navigate with arrow keys inside the menu

### Expected result

Menu entries with a submenu are output as such, i.e. there is a reference to the submenu.

For example, NVDA correctly outputs the reference to the submenu due to aria-haspopup.

### Actual result

There is no reference to the submenu. Menu entries with a submenu cannot be distinguished from entries without a submenu. This is a serious problem because it prevents the operation of the menus

### Example

https://w3c.github.io/aria-practices/examples/menubar/menubar-navigation.html

#### JAWS version and build number

JAWS 18
JAWS 2019
JAWS 2020 (current version and older versions)

 #### Operating System and version

Windows 8
Windows 10

#### Browser and version:

current versions of Chrome, Firefox ESR and IE 11

Testing with Firefox (without ESR) is not possible because Firefox crashes immediately when used with JAWS

**Comment by frex65** [comment]
Some interesting observations using JAWS 2020.2004.66:
*	In IE11 and Firefox 68 ESR JAWS flags up the presence of a submenu.
*	In Chrome 84, JAWS flags up the presence of a submenu when a parent menuitem is encountered using the virtual cursor, but not using the Tab key.
*	ARIA attributes are slightly different in Chrome and FF (attempting to inspect these menuitem elements in IE11 causes it to crash):
  *	Chrome:
    *	role=”menuitem”
    *	hasPopup=“menu”
  *	Firefox:
    *	role=”parent menuitem”
    *	haspopup=”true”

**Comment by frex65** [comment]
@BenKeyFSI  @kurtjwolf  please can you log this issue as a bug in JAWS 2020/Crhome 84. Thanks.

**Comment by dfarough** [comment]
I cannot Believe that this issue is closed. 
surely it is important for Jaws users to know if a menu item contains additional content.
If this is obvious to a person with good vision why should we not be aware of this as well.
This has been an issue for a long time.
JAWS users deserve better from Vispero.Screen

**Comment by JAWS-test** [comment]
@dfarough 

It is not closed. I just retested with JAWS 2021 and 2022. The problem still exists. I cannot understand why it is not possible to solve such a serious problem within 2 years

**Comment by jducrot** [comment]
I can confirm that this bug is alive and well with the latest version of JAWS 2023 while NVDA announces this pattern correctly. An easy place to test this is the codepen included on the W3C [APG's menubar pattern page ](https://codepen.io/HEA11Y/pen/poYjOmX). 

Hopefully this gets some attention because even though devs shouldn't use the menu pattern for navigation we all know they do it all over the place and that means even when they get the semantics correctly, JAWS users don't benefit.

**Comment by dfarough** [comment]
This is working for me using Jaws version 2024.2310.70.
I tested using the “APG's menubar pattern page

**Comment by stevefaulkner** [comment]
tested with JAWS 2024 and chrome Version 120.0.6099.130 (Official Build) (64-bit) Works as expected. items with submenus are announced.
