### ISSUE TITLE
JAWS not reading all info about slider in reading mode

### ISSUE THREAD

**Issue by stevefaulkner** [FreedomScientific/standards-support#727]
### Summary
JAWS Reads all information about a slider in reading mode when using the INSERT+TAB keys "Red left right slider  128 min 0 max 255", does not when using INSERT+UpArrow keys. "128  left right slider"

Example:
 1. Go to https://aria-at.netlify.app/tests/horizontal-slider/reference/2022-4-11_11511/slider-color-viewer.setfocusonredslider
 2. focus the red slider
 3. press escape to enter virtual PC cursor mode
 4. press INSERT+UpArrow

### Expected result

> Red left right slider  128 min 0 max 255

### Actual result

> 128  left right slider

### Additional Information
[ARIA AT  - Color Viewer Slider with JAWS and Firefox](https://aria-at.w3.org/report/2369/targets/195#result-NDZjZeyIxMiI6NDUyfQWZmZj)

#### JAWS version and build number
2303.2306.38

 
#### Operating System and version
windows 10

#### Browser and version:
Firefox 116.0b1 (64-bit)

**Comment by stevefaulkner** [comment]
cc @RFischer-FS

**Comment by RFischer-FS** [comment]
Hello Steven,
Let me provide some background regarding your question:
1) **Insert + Tab** (Say Window Prompt and text)
This keystroke should announce the current element with its information. (Side note: The word 'window', refers to a window handle, nowadays this the word element is more common.)

2) **Insert+Up** (SayCurrentLine)
This keystroke should announce the current line. Pressing the keystroke twice lets JAWS spell the line. 

In some scenarios, the keystrokes provide a similar output, but overall the Insert+Tab provides more details than Insert+Up.

**Comment by stevefaulkner** [comment]
JAWS commands:
 INSERT+UpArrow = Say current line
INSERT+TAB = Say Window Prompt in Text

**Comment by stevefaulkner** [comment]
@RFischer-FS @ so question for us is, do we think that the different keystroke combinations need to be equivalent?

**Comment by BrettLewisVispero** [comment]
One other point here, if you navigate in the virtual buffer with manual forms mode, we do read the insert+tab output.
Since we do that, I could see an argument that we should announce the same thing for say line.

**Comment by stevefaulkner** [comment]
The Issue of concern here (i think) is that INSERT+UP does not announce the accessible name of the control, not that it is less verbose than INSERT+TAB.

I think that JAWS should announce "Red" in this case being the acc name of the control

### Expected result
Red left right slider 128

### Actual result
128 left right slider

**Comment by BrettLewisVispero** [comment]
Imported into ADO as bug 36701

**Comment by mcking65** [comment]
In general, when reading with the VC, It seems to me that SayLine should repeat whatever SayNextLine or SayPriorLine had just announced.

Currently, if the VC is active and I press down arrow and land on a slider, I am hearing the name, role, value, min, and max. If I press insert+Up, it seems that I should hear the same thing.

When in forms mode, where you are changing the value and can't read the value by character with left/right, I think there is a good argument that insert+up and insert+tab should be different. hearing min/max with insert+up could make it hard to hear the current value by adding a lot of speech after the value. So, in forms mode, perhaps min/max should only be announced with insert+tab.

@BrettLewisVispero , I think there are more opportunities to make sliders easier to understand here. Currently orientation is announced as part of the role. That is pretty verbose. I can imagine some people getting confused and thinking the orientation is part of the name, e.g., red left right slider.

I don't know if there is a strong need for orientation to be announced in virtual cursor mode because you can't adjust the slider with the VC. I'd argue that announcing orientation in reading mode should be optional. So, the VC output could be:

>Red slider 128 min 0 max 255

I think that output could be made even easier to understand if the min and max were announced with the message voice.

In forms mode, on the other hand, knowing orientation is a bit more important, especially for users who are less familiar with how to operate a slider. One way this could be made easier to understand is to only speak orientation in the tutor message like this ...

>Red slider 128 min 0 max 255 To increase or decrease, use left and right arrow keys

**Comment by BrettLewisVispero** [comment]
Fixed in JAWS 2024
